### ISSUE TITLE
lnd panic while syncing

### ISSUE THREAD

**Issue by Cocosoft** [lightninglabs/neutrino#21]
Hi!
While syncing the Lighting Desktop app on Windows 10, I got the following error:

```
lnd Error: panic: Rollback failed: truncate C:\Users\Coco\AppData\Local\Lnd\data\testnet3\bitcoin\reg_filter_headers.bin: Access is denied. goroutine 50 [running]: github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).handleHeadersMsg(0xc0424b88c0, 0xc044ed05e0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:1085 +0x1d3a github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).blockHandler(0xc0424b88c0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:347 +0x434
lnd Error: created by github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).Start /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:200 +0x11b
```

**Comment by drunkenclam** [comment]
Got the same error.

Workaround: Exit the app, delete block_headers.bin, ext_filter_headers.bin and reg_filter_headers.bin and start again.

**Comment by dlogemann** [comment]
Got this error yesterday and I got this resolved using the workaround:
- quit the app
- deleted the three files
- started again and 
- synced fully again 
The app worked successfully. 

I closed the app normally yesterday, and today I get the same error again. OS is Windows 10.

**Comment by aakselrod** [comment]
This error seems to be happening in a Windows environment when the blockchain is rolled back due to a reorg. Windows appears to only allow a program to truncate a file when it's closed, so on Windows, we'll need to close/truncate/reopen the header flat files. A fix is forthcoming shortly.

**Comment by Cocosoft** [comment]
Thanks for the update @aakselrod :)

**Comment by drunkenclam** [comment]
Still have an issue with this in alpha 0.1.1

Log says:

```
lnd Error: panic: Rollback failed: truncate C:\Users\Daniel\AppData\Local\Lnd\data\testnet3\bitcoin\reg_filter_headers.bin: Zugriff verweigert goroutine 50 [running]:
lnd Error: github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).handleHeadersMsg(0xc0420669a0, 0xc0421a3140) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:1085 +0x1d3a github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).blockHandler(0xc0420669a0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:347 +0x434 created by github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).Start /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:200 +0x11b
```

**Comment by Roasbeef** [comment]
@drunkenclam this change didn't make it into that version of the application. It will be in the _next_ release though
